default_platform(:android)

platform :android do
  #PUBLIC 
  desc "Build and test application"
  lane :build_test do
    lintKotlin()
    unit_test()
  end

  desc "Build, test and deploy application"
  lane :build_test_deploy do
    lintKotlin()
    unit_test()
    deploy()
  end

  desc "Run Kotlinter for lint checks"
    lane :lintKotlin do
      gradle(task: "lintKotlin")
    end

  desc "Runs unit tests"
  private_lane :unit_test do
    gradle(task: "testDebugUnitTest")
  end

  desc "Deploy a new version to Firebase app distribution"
  private_lane :deploy do
    gradle(
        task: "clean assemble",
        build_type: "release",
        print_command: true,
    )
    firebase_app_distribution(
        service_credentials_file: "service_credentials_file.json",
        app: ENV['FIREBASE_APP_ID'],
        android_artifact_type: "APK",
        release_notes_file: "release_note.txt"
    )
  end

end