# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics

    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Distributing the app through fírebase"
      lane :distribute do
          gradle(task: "clean assembleRelease")
          firebase_app_distribution(
              app: "1:836297389341:android:0f4c9711bb3bdbf2189df4",
              android_artifact_type: "APK",
              firebase_cli_token: "1//0coanuMswLO4bCgYIARAAGAwSNwF-L9IrYQxheDM8maWmC5LexRQPweJuZlRYAQPtJ-ocwmq8kKc5ouDw32UQVpBwN4uaCIYkI-w",
              release_notes_file: "release_note.txt"
          )
      end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
