name: react-native-android-build-apk
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v1

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.4

      - name: Build and test
        uses: maierj/fastlane-action@v2.0.0
        with:
          lane: "build_test"