name: Build and test android app

on:
  push:
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v1

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2

      - name: Install bundle
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: Create Service Credentials file
        run: |
          echo ${SERVICE_CREDENTIALS_FILE} | base64 -d > service_credentials_file.json
        env:
          SERVICE_CREDENTIALS_FILE: ${{ secrets.SERVICE_CREDENTIALS_FILE }}

      - name: Run lint, build and test
        run: bundle exec fastlane build_test