name: build test and deploy android app
on:
  push:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v1

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2

      - name: Install bundle
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: Create Service Credentials file
        run: |
          echo "$SERVICE_CREDENTIALS_FILE" > service_credentials.json.b64
          base64 -d -i service_credentials.json.b64 > service_credentials_file.json
        env:
          SERVICE_CREDENTIALS_FILE: ${{ secrets.SERVICE_CREDENTIALS_FILE }}

      - name: Setup keystore properties
        env:
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          KEYSTORE_FILE_NAME: ${{ secrets.KEYSTORE_FILE_NAME }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        run: |
          printf 'keyAlias=%s\nkeyPassword=%s\nstoreFile=%s\nstorePassword=%s' \
          ${KEY_ALIAS} ${KEY_PASSWORD} ${STORE_FILE_NAME} ${STORE_PASSWORD} > keystore/keystore.properties          

      - name: Decode keystore file
        env:
          KEYSTORE_FILE: ${{ secrets.KEYSTORE_FILE }}
          KEYSTORE_FILE_NAME: ${{ secrets.KEYSTORE_FILE_NAME }}
        run: |
          echo ${KEYSTORE_FILE} | base64 -d >${KEYSTORE_FILE_NAME}

      - name: Distribute app with 🔥 App Distribution 🚀
        run: bundle exec fastlane build_test_deploy
        env:
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}