name: Build test and deploy android app

on:
  push:
    branches: [ "feature/*" ]
env:
  VERSION_CODE: 1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Find the total number of commits
        run: |
          echo "Running the numbers"
          echo "CODE=$(echo git rev-list --all --count" >> $VERSION_CODE

      - name: Bump version
        uses: mad9000/actions-find-and-replace-string@2
        id: version_name
        with:
          source: ${{ github.ref_name }}
          find: 'feature/'
          replace: ''

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2

      - name: Install bundle
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: Create Service Credentials file
        run: |
          echo ${SERVICE_CREDENTIALS_FILE} | base64 -d > service_credentials_file.json
        env:
          SERVICE_CREDENTIALS_FILE: ${{ secrets.SERVICE_CREDENTIALS_FILE }}

      - name: Run lint, build and test
        run: bundle exec fastlane build_test_deploy